### ISSUE TITLE
Exposed API Key

### ISSUE THREAD

**Issue by nahatx** [RobPruzan/Transform#8]
https://github.com/RobPruzan/Transform/blob/5215d095dc6593bd8bfbb0999ad1db399ebde50f/hackathon/api/views.py#L39

Howdy,

Do not expose your API key in your source code.

Instead, consider storing it an environment variable, or using a key management service, or even software such as Vault.
Then be sure to rotate your API key after it is safely stored, or else it may still be recoverable in your commit history.

Also, see Openai's best practices page for api keys for more details:
https://help.openai.com/en/articles/5112595-best-practices-for-api-key-safety

**Comment by RobPruzan** [comment]
Appreciate the help, but all is good, this key has been broken for a while. Forgot I had it outside an env file and pushed it
